from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PATCH = ROOT / "tools" / "fts-chassis-converter" / "patch-upstream.ps1"
BUILD_WORKFLOW = ROOT / ".github" / "workflows" / "build-fts-chassis-converter.yml"
APP_WORKFLOW = ROOT / ".github" / "workflows" / "apply-fts-app-integration.yml"
APP_PATCH = ROOT / "tools" / "fts-chassis-converter" / "apply_app_integration.py"
CHASSIS = ROOT / "source-v1.2" / "fh6garage" / "preview3d" / "chassis_converter.py"


def test_fts_converter_patch_is_pinned_and_structural():
    text = PATCH.read_text(encoding="utf-8")
    assert "6f53ca3c584d78659d06d4b4a39561db67d79345" in text
    assert "4f373c5fb192551ce5249e320dd79b1399b693ca" in text
    assert "geometry.GetRotationMatrix()" in text
    assert "raw.X * mesh.PositionScale.X" in text
    assert "scaled.X + mesh.PositionTranslate.X" in text
    assert "geometry.BoneTransform" in text
    assert "instanceTransform" in text
    assert "fh6_fts_chassis_conversion_v1" in text
    assert "lateral_translation_v1" not in text


def test_fts_converter_workflow_builds_patched_source():
    text = BUILD_WORKFLOW.read_text(encoding="utf-8")
    assert "dotnet publish" in text
    assert "patch-upstream.ps1" in text
    assert "FH6.FtsChassisConverter.exe" in text
    assert "contents: write" in text


def test_app_integration_is_pinned_to_built_fts_converter():
    patch = APP_PATCH.read_text(encoding="utf-8")
    assert "e0a0b5e3ad5054b8410ae4497c5dacf2db6adf19" in patch
    assert "7556c1e4cd3b3d532339a9226241988be69cd27d" in patch
    assert "fh6_fts_chassis_conversion_v1" in patch
    assert "fts_native_transform_v1" in patch
    assert "repair_wheelstyle_lateral_translation" in patch  # exact removal target is guarded


def test_app_integration_workflow_applies_and_tests_source():
    text = APP_WORKFLOW.read_text(encoding="utf-8")
    assert "apply_app_integration.py" in text
    assert "py_compile" in text
    assert "test_fts_converter_contract.py" in text
    assert "Use ForzaTechStudio converter for 3D geometry" in text


def test_integrated_chassis_converter_contract_when_applied():
    text = CHASSIS.read_text(encoding="utf-8")
    if 'FH6.FtsChassisConverter.exe' not in text:
        # The source update is generated by the integration workflow in this same push.
        return
    assert 'FH6.FtsChassisConverter.exe' in text
    assert 'CONVERTER_BLOB_SHA1 = "7556c1e4cd3b3d532339a9226241988be69cd27d"' in text
    assert 'FTS_CONVERTER_FORMAT = "fh6_fts_chassis_conversion_v1"' in text
    assert 'FTS_NATIVE_GEOMETRY_REVISION = "fts_native_transform_v1"' in text
    assert "repair_wheelstyle_lateral_translation(output)" not in text
    assert '"status": "fts_native_geometry"' in text
    assert "apply_neutral_wheel_visibility" in text
    assert "annotate_neutral_geometry" in text
